services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    volumes:
      - ./external.conf:/etc/lighttpd/external.conf
      - ./data/pihole:/etc/pihole
      - ./data/dnsmasq.d:/etc/dnsmasq.d
      # - /var/log/pihole/pihole.log:/var/log/pihole/pihole.log
      # - /var/log/pihole/FTL.log:/var/log/pihole/FTL.log
    ports:
      - "5300:53"
      - "5300:53/udp"
      - "67:67/udp"
      - "5200:80"
    environment:
      - TZ=America/New_York
      - FTLCONF_webserver_api_password=${APP_PASSWORD}
      - VIRTUAL_HOST=${APP_HOST_URL}
      - WEBTHEME=default-darker
    restart: unless-stopped

