services:
  mailpit:
    image: axllent/mailpit:latest
    restart: always
    ports:
      # The port your application will connect to using SMTP
      - "25:1025"
      # The port to access the web interface in your browser
      - "8025:8025"

