services:
  ntp:
    build: .
    image: simonrupf/chronyd:latest
    container_name: ntp
    restart: always
    read_only: true
    tmpfs:
      - /etc/chrony:rw,mode=1750,uid=100,gid=101
      - /run/chrony:rw,mode=1750,uid=100,gid=101
      - /var/lib/chrony:rw,mode=1750,uid=100,gid=101
    ports:
      - 123:123/udp
    cap_add:
      - CAP_NET_BIND_SERVICE
      - SYS_TIME
    user: "0:0"
    devices:
      - /dev/ptp0:/dev/ptp0
    environment:
      - NTP_SERVERS=time.cloudflare.com
      - LOG_LEVEL=0
      - TZ=America/Mew_York
      - NOCLIENTLOG=false
      - ENABLE_NTS=true
      - ENABLE_SYSCLK=true
